// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeD_rRGNosBG0ChJX_MIFNSLcVEIDGf54',
    appId: '1:389553378831:web:efb3912075cb5686d1b57a',
    messagingSenderId: '389553378831',
    projectId: 'chat-app-bd61a',
    authDomain: 'chat-app-bd61a.firebaseapp.com',
    storageBucket: 'chat-app-bd61a.appspot.com',
    measurementId: 'G-GQXCTKMQXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEja1RZ_f39UItT0IBUKGk-rUybSWYhBs',
    appId: '1:389553378831:android:25f87b1fb8888ea4d1b57a',
    messagingSenderId: '389553378831',
    projectId: 'chat-app-bd61a',
    storageBucket: 'chat-app-bd61a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPkPIDD63ol3Av5TqnRY4ZEQqueWZ3oj8',
    appId: '1:389553378831:ios:aac48081a9acf41bd1b57a',
    messagingSenderId: '389553378831',
    projectId: 'chat-app-bd61a',
    storageBucket: 'chat-app-bd61a.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPkPIDD63ol3Av5TqnRY4ZEQqueWZ3oj8',
    appId: '1:389553378831:ios:14013fa12f61eebdd1b57a',
    messagingSenderId: '389553378831',
    projectId: 'chat-app-bd61a',
    storageBucket: 'chat-app-bd61a.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
